# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prerequisites on the host:
# - brew install bash bison coreutils ninja cmake
# - sudo arrow/ci/scripts/install_python.sh macos 3.9


# NOTE: must set "Crossbow" as name to have the badge links working in the
# github comment reports!
name: Crossbow
on:
  push:
    branches:
      - "*-github-*"


env:
  ARROW_JEMALLOC: OFF
  CC: "clang"
  CMAKE_BUILD_TYPE: release
  CMAKE_CXX_COMPILER_LAUNCHER: "ccache"
  CXX: "clang++"
  MACOSX_DEPLOYMENT_TARGET: "11.0"
  PYARROW_BUILD_VERBOSE: 1
  PYARROW_VERSION: "16.0.0.dev232"
  PYTHON_VERSION: "3.8"
  PYTHON: "/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8"
  VCPKG_FEATURE_FLAGS: "manifests"
  VCPKG_OVERLAY_TRIPLETS: ${{ github.workspace }}/arrow/ci/vcpkg
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build:
    name: Build wheel for Python 3.8 on macOS
    runs-on: ["self-hosted", "macOS", "arm64"]
    steps:
      - name: Cleanup
        run: rm -rf arrow vcpkg build crossbow-env build-*-env test-*-env

      - name: Checkout Arrow
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: arrow
          repository: apache/arrow
          ref: ee1a8c39a55f3543a82fed900dadca791f6e9f88
          submodules: recursive


      - name: Add Brew's Bison to PATH
        run: echo "/opt/homebrew/opt/bison/bin" >> $GITHUB_PATH

      - name: Retrieve VCPKG version from arrow/.env
        run: |
          vcpkg_version=$(cat "arrow/.env" | grep "VCPKG" | cut -d "=" -f2 | tr -d '"')
          echo "VCPKG_VERSION=$vcpkg_version" >> $GITHUB_ENV

      - name: Install Vcpkg
        env:
          MACOSX_DEPLOYMENT_TARGET: "11.0"
        run:  arrow/ci/scripts/install_vcpkg.sh $VCPKG_ROOT $VCPKG_VERSION

      - name: Add Vcpkg to PATH
        run: echo ${VCPKG_ROOT} >> $GITHUB_PATH

      - name: Install ARM64 Packages
        env:
          VCPKG_DEFAULT_TRIPLET: arm64-osx-static-release
        run: |
          vcpkg install \
            --clean-after-build \
            --x-install-root=${VCPKG_ROOT}/installed \
            --x-manifest-root=arrow/ci/vcpkg \
            --x-feature=azure \
            --x-feature=flight \
            --x-feature=gcs \
            --x-feature=json \
            --x-feature=parquet \
            --x-feature=s3

      - name: Build ARM64 Wheel
        env:
          ARROW_SIMD_LEVEL: "DEFAULT"
          VCPKG_DEFAULT_TRIPLET: arm64-osx-static-release
        run: |
          $PYTHON -m venv build-arm64-env
          source build-arm64-env/bin/activate
          pip install --upgrade pip wheel
          arrow/ci/scripts/python_wheel_macos_build.sh arm64 $(pwd)/arrow $(pwd)/build

      - uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: arrow/python/repaired_wheels/*.whl

      - name: Test Wheel on ARM64
        shell: bash
        env:
          PYTEST_ADDOPTS: "-k 'not test_cancellation'"
        run: |
          $PYTHON -m venv test-arm64-env
          source test-arm64-env/bin/activate
          pip install --upgrade pip wheel
          # libffi has to be installed on the m1 runner which causes issues with 
          # the cffi wheel. We build cffi with the flags pointing to the correct libffi location.
          LDFLAGS=-L$(brew --prefix libffi)/lib CFLAGS=-I$(brew --prefix libffi)/include \
             pip install cffi --no-binary :all:
          pip install -r arrow/python/requirements-wheel-test.txt
          PYTHON=python  arrow/ci/scripts/install_gcs_testbench.sh default
          arrow/ci/scripts/python_wheel_unix_test.sh $(pwd)/arrow

      - name: Upload artifacts
        shell: bash
        run: |
          $PYTHON -m venv crossbow-env
          source crossbow-env/bin/activate
          arch -x86_64 pip install -e arrow/dev/archery[crossbow-upload]
          arch -x86_64 archery crossbow \
            --queue-path $(pwd) \
            --queue-remote https://github.com/ursacomputing/crossbow \
            upload-artifacts \
            --sha nightly-packaging-2024-03-06-0-github-wheel-macos-big-sur-cp38-arm64 \
            --tag nightly-packaging-2024-03-06-0-github-wheel-macos-big-sur-cp38-arm64 \
            "arrow/python/repaired_wheels/*.whl"
        env:
          CROSSBOW_GITHUB_TOKEN: ${{ secrets.CROSSBOW_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Set up Ruby by apt
        if: runner.os == 'Linux' && runner.arch != 'X64'
        run: |
          sudo apt update
          sudo apt install -y ruby-full
      - name: Set up Ruby by GitHub Actions
        if: runner.arch == 'X64' && runner.os != 'macOS'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "ruby"
      - name: Install gemfury client on ARM self-hosted
        if: runner.arch != 'X64'
        run: |
          # GH-36692: Pin gemfury due to wrong faraday dependency declaration.
          gem install --user-install gemfury -v 0.12.0
          ruby -r rubygems -e 'puts("#{Gem.user_dir}/bin")' >> $GITHUB_PATH
      - name: Install gemfury client
        if: runner.arch == 'X64'
        run: |
          # GH-36692: Pin gemfury due to wrong faraday dependency declaration.
          gem install gemfury -v 0.12.0
      - name: Upload package to Gemfury
        shell: bash
        run: |
          fury push \
            --api-token=${CROSSBOW_GEMFURY_TOKEN} \
            --as=${CROSSBOW_GEMFURY_ORG} \
            arrow/python/repaired_wheels/*.whl
        env:
          CROSSBOW_GEMFURY_TOKEN: ${{ secrets.CROSSBOW_GEMFURY_TOKEN }}
          CROSSBOW_GEMFURY_ORG: ${{ secrets.CROSSBOW_GEMFURY_ORG }}
