# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.



# NOTE: must set "Crossbow" as name to have the badge links working in the
# github comment reports!
name: Crossbow
on:
  push:
    branches:
      - "*-github-*"

env:
  ARCHERY_DEBUG: 1
  ARCHERY_USE_DOCKER_CLI: 1


jobs:
  source:
    # This job will change the version to either the custom_version param or YMD format.
    # The output allows other steps to use the exact version to prevent issues (e.g. date changes during run)
    name: Source Package
    runs-on: ubuntu-latest
    outputs:
      pkg_version: ${{ steps.save-version.outputs.pkg_version }}
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: arrow
          repository: amol-/arrow
          ref: 0a6e36737a8fa3fb92342a0bae5ac5ddb8669749
          submodules: recursive

      - name: Modify version
        shell: bash
        run: |
          cd arrow/r
          sed -i.bak -E -e \
            's/(^Version: )([0-9]+\.[0-9]+\.[0-9]+).*$/\117.0.0.100000068/' \
            DESCRIPTION
          head DESCRIPTION
          rm -f DESCRIPTION.bak

      - name: Save Version
        id: save-version
        shell: bash
        run: |
          echo "pkg_version=$(grep ^Version arrow/r/DESCRIPTION | sed s/Version:\ //)" >> $GITHUB_OUTPUT

      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false

      - name: Build R source package
        shell: bash
        run: |
          cd arrow/r
          # Copy in the Arrow C++ source
          make sync-cpp
          R CMD build --no-build-vignettes .

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: r-pkg__src__contrib
          path: arrow/r/arrow_*.tar.gz

  
  test-source:
    needs: source
    name: Test ${{ matrix.platform.name }} source build
    runs-on: ${{ matrix.platform.runs_on }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - {runs_on: "ubuntu-24.04", name: "Linux"}
    steps:
      - name: Install R
        uses: r-lib/actions/setup-r@v2
      # TODO: improve arg handling
      - name: Setup local repo
        shell: bash
        run: mkdir repo
      - name: Get src pkg
        uses: actions/download-artifact@v3
        with:
          name: r-pkg__src__contrib
          path: repo/src/contrib
      - name: Update repo index
        shell: Rscript {0}
        run: |
          # getwd() is necessary as this macro is used within jobs using a docker container
          tools::write_PACKAGES(file.path(getwd(), "repo/src/contrib", fsep = "/"), type = "source", verbose = TRUE)
      - name: Show repo
        shell: bash
        # tree not available in git-bash on windows
        run: |
          ls -R repo
      - name: Add repos to .Rprofile
        shell: Rscript {0}
        run: |
          profile_path <- file.path(getwd(), ".Rprofile")
          repo <- paste0("file://", getwd(), "/repo")
          str <- paste0("options(arrow.repo = '", repo, "' )")
          print(str)
          write(str, file = profile_path, append = TRUE)
          str <- paste0("options(arrow.dev_repo = '", repo, "' )")
          print(str)
          write(str, file = profile_path, append = TRUE)
          # Set envvar for later steps by appending to $GITHUB_ENV
          write(paste0("R_PROFILE_USER=", profile_path), file = Sys.getenv("GITHUB_ENV"), append = TRUE)

      - name: Checkout Arrow
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: arrow
          repository: amol-/arrow
          ref: 0a6e36737a8fa3fb92342a0bae5ac5ddb8669749
          submodules: recursive

      - name: Install sccache
        if: matrix.platform.name == 'Linux'
        shell: bash
        run: |
          arrow/ci/scripts/install_sccache.sh unknown-linux-musl /usr/local/bin
      - name: Install R package system dependencies (Linux)
        if: matrix.platform.name == 'Linux'
        run: sudo apt-get install -y libcurl4-openssl-dev libssl-dev
      - name: Install R package system dependencies (macOS)
        if: matrix.platform.name == 'macOS'
        run: brew install sccache openssl curl
      - name: Remove arrow/
        run: |
          rm -rf arrow/
      - name: Enable parallel build
        run: |
          cores=`nproc || sysctl -n hw.logicalcpu`
          echo "MAKEFLAGS=-j$cores" >> $GITHUB_ENV
      - name: Install arrow source package
        env:
          # Test source build so be sure not to download a binary
          LIBARROW_BINARY: "FALSE"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          SCCACHE_BUCKET: "${{ secrets.SCCACHE_BUCKET }}"
          SCCACHE_REGION: "${{ secrets.SCCACHE_REGION }}"
          SCCACHE_S3_KEY_PREFIX: "sccache"

        shell: Rscript {0}
        run: |
          source("https://raw.githubusercontent.com/apache/arrow/HEAD/ci/etc/rprofile")

          # always remove arrow (mainly for self-hosted runners)
          try(remove.packages("arrow"), silent = TRUE)

          install.packages(
            "arrow",
            repos = c(getOption("arrow.dev_repo"), getOption("repos")),
            verbose = TRUE,
            type = "source",
            INSTALL_opts = "--build"
          )

          library(arrow)
          read_parquet(system.file("v0.7.1.parquet", package = "arrow"))
          print(arrow_info())

          # Our Version should always be > CRAN so we would detect a CRAN version here.
          stopifnot(packageVersion("arrow") == "${{needs.source.outputs.pkg_version}}")


      - name: Retry with verbosity if that failed
        if: failure()
        env:
          LIBARROW_BINARY: "FALSE"
          ARROW_R_DEV: "TRUE"
          CMAKE_FIND_DEBUG_MODE: "ON"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          SCCACHE_BUCKET: "${{ secrets.SCCACHE_BUCKET }}"
          SCCACHE_REGION: "${{ secrets.SCCACHE_REGION }}"
          SCCACHE_S3_KEY_PREFIX: "sccache"

        shell: Rscript {0}
        run: |
          source("https://raw.githubusercontent.com/apache/arrow/HEAD/ci/etc/rprofile")

          # always remove arrow (mainly for self-hosted runners)
          try(remove.packages("arrow"), silent = TRUE)

          install.packages(
            "arrow",
            repos = c(getOption("arrow.dev_repo"), getOption("repos")),
            verbose = TRUE,
            type = "source",
            INSTALL_opts = "--build"
          )

          library(arrow)
          read_parquet(system.file("v0.7.1.parquet", package = "arrow"))
          print(arrow_info())

          # Our Version should always be > CRAN so we would detect a CRAN version here.
          stopifnot(packageVersion("arrow") == "${{needs.source.outputs.pkg_version}}")


 
